version: '3.8'

services:
  tiktok-live:
    build:
      context: .
      no_cache: true
    container_name: tiktok-live-viewer
    ports:
      - "8080:8080"
    environment:
      - TIKTOK_USERNAME=n0slack
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
    stdin_open: true
    tty: true